---
title: "12-DT-iris"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: united
---

### Code Accompanying ***The Machine Learning Handbooks***, Volume I, Chapter 12

#### Book pdf is available on the GitHub repo: https://github.com/kjmazidi/Machine_Learning_3rd_edition

###### Copyright KJG Mazidi

### Introduction

This notebook explores the rpart and tree implementations of decision trees on the iris data. 

Library imports: 

* rpart
* tree


```{r, warning = FALSE, message = FALSE}

if (!require(rpart)){
  install.packages("rpart")
}
library("rpart")


if (!require(tree)){
  install.packages("tree")
}
library("tree")
```


### Using rpart


```{r}
# uses library(rpart)
tree_iris <- rpart(Species~., data=iris, method="class")
tree_iris
summary(tree_iris)
plot(tree_iris, uniform=TRUE)
text(tree_iris, use.n=TRUE, all=TRUE, cex=.6)
```

### Using tree

```{r}
# uses library(tree)
tree_iris2 <- tree(Species~., data=iris)
tree_iris2
summary(tree_iris2)
plot(tree_iris2)
text(tree_iris2, cex=0.5, pretty=0)
```

### train and test

```{r}

set.seed(1958)
i <- sample(150, 100, replace=FALSE)
train <- iris[i,]
test <- iris[-i,]
tree_iris3 <- tree(Species~., data=train)
pred <- predict(tree_iris3, newdata=test, type="class")
table(pred, test$Species)
mean(pred==test$Species)
```


